### ISSUE TITLE
Návrh UI

### ISSUE THREAD

**Issue by marcel3032** [TIS2021-FMFI/prebalovanie#16]
návrh je zásade hotový od gefca [tu](https://github.com/TIS2021-FMFI/prebalovanie/blob/9daea952beeb2e37158614c94a57f8de4f15a5a1/docs/GEFCO_ZAVAR_-_Aplik%C3%A1cia_PREBAL_WRP_2021.pdf)

**Comment by lenkadermiskova** [comment]
[GEFCO_ZAVAR_-_Aplikácia_PREBAL_WRP_2021.pptx](https://github.com/TIS2021-FMFI/prebalovanie/files/7466630/GEFCO_ZAVAR_-_Aplikacia_PREBAL_WRP_2021.pptx)

**Comment by marcel3032** [comment]
asi fajn, tak to treba teda hodiť na git :)
