### ISSUE TITLE
testovacie scenáre 26.11.

### ISSUE THREAD

**Issue by marcel3032** [TIS2021-FMFI/prebalovanie#21]
Aby sa otestovala každá požiadavka aspoň v 1 scenári

**Comment by matej141** [comment]
https://docs.google.com/document/d/1u_lZXreQkzUuaY-4kV_I2o2ZRahynpWKJWcWFLGDL3I/edit?usp=sharing

**Comment by marcel3032** [comment]
toto teda treba poriadne reviewnuť, a potom exportnúť do pdf a nahrať na git
