### ISSUE TITLE
Návrh 12.11.

### ISSUE THREAD

**Issue by marcel3032** [TIS2021-FMFI/prebalovanie#27]
- [x] #11 @generic1707 
- [x] #16 @lenkadermiskova 
- [x] #20 @marcel3032 
- [x] #21 @matej141 
- [x] #29

**Comment by lenkadermiskova** [comment]
[GEFCO_ZAVAR_-_Aplikácia_PREBAL_WRP_2021.pptx](https://github.com/TIS2021-FMFI/prebalovanie/files/7466243/GEFCO_ZAVAR_-_Aplikacia_PREBAL_WRP_2021.pptx)

Návrh -- bod C
